name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
    - '.github/workflows/ci.yml'
    - 'src/**'
    - 'test/**'
    - 'Kiyote.Files.sln'
    - 'Directory.Packages.props'
    - 'Directory.Build.props'
    - 'nuget.config'
  push:
    branches: [main]

permissions:
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --logger "Console;Verbosity=normal"
      
      - name: Create Orphan Branch
        shell: bash
        run: ${{ github.workspace }}/create-orphan-branch.sh badges ${{ github.ref_name }}
    
      - name: Install dotnet-coverage
        run: dotnet tool install dotnet-coverage
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Generate coverage file
        run: dotnet dotnet-coverage merge -r -o coverage.xml coverage.cobertura.xml -f cobertura
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Make Coverage Badge      
        uses: action-badges/cobertura-coverage-xml-badges@0.3.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./coverage.xml    
